application: your-app-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /cron/remove_deactivated_user_accounts
  script: cron.app
  login: admin

- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: 2.5.2

env_variables:
  ######   DEVELOPMENT
  FLASK_CONFIG: 'development'
  SECRET_KEY: 'the development key'

  # ######   PRODUCTION
  # FLASK_CONFIG: 'production'
  # SECRET_KEY: 'a super-secret long and random value'
